# -*- coding: utf-8 -*-
import json

rosters = {
"الجزائر": ["Luca Zidane","Oussama Benbot","Melvin Mastil","Abdelatif Ramdane","Aissa Mandi","Ramy Bensebaini","Mohamed Amine Tougai","Rayan Ait-Nouri","Jaouen Hadjam","Rafik Belghali","Zineddine Belaid","Achref Abada","Samir Chergui","Nabil Bentaleb","Ramiz Zerrouki","Hicham Boudaoui","Fares Chaibi","Houssem Aouar","Ibrahim Maza","Yacine Titraoui","Riyad Mahrez","Mohamed Amoura","Amine Gouiri","Anis Hadj Moussa","Adil Boulbina","Nadhir Benbouali","Fares Ghedjemis"],
"الأرجنتين": ["Emiliano Martinez","Geronimo Rulli","Juan Musso","Gonzalo Montiel","Nahuel Molina","Lisandro Martinez","Nicolas Otamendi","Leonardo Balerdi","Cristian Romero","Nicolas Tagliafico","Facundo Medina","Giovani Lo Celso","Leandro Paredes","Rodrigo De Paul","Exequiel Palacios","Enzo Fernandez","Alexis Mac Allister","Valentin Barco","Lionel Messi","Nicolas Gonzalez","Giuliano Simeone","Lautaro Martinez","Jose Manuel Lopez","Julian Alvarez","Thiago Almada","Nico Paz"],
"أستراليا": ["Mathew Ryan","Paul Izzo","Patrick Beach","Milos Degenek","Alessandro Circati","Jacob Italiano","Jordan Bos","Jason Geria","Kai Trewin","Aziz Behich","Harry Souttar","Cameron Burgess","Lucas Herrington","Connor Metcalfe","Ajdin Hrustic","Aiden O'Neill","Cammy Devlin","Jackson Irvine","Paul Okon-Engstler","Mathew Leckie","Mohamed Toure","Awer Mabil","Nestory Irankunda","Cristian Volpato","Nishan Velupillay","Tete Yengi"],
"النمسا": ["Alexander Schlager","Florian Wiegele","Patrick Pentz","David Affengruber","Kevin Danso","Stefan Posch","David Alaba","Philipp Lienhart","Phillipp Mwene","Alexander Prass","Marco Friedl","Michael Svoboda","Xaver Schlager","Nicolas Seiwald","Marcel Sabitzer","Florian Grillitsch","Carney Chukwuemeka","Romano Schmid","Christoph Baumgartner","Konrad Laimer","Patrick Wimmer","Paul Wanner","Alessandro Schopf","Marko Arnautovic","Michael Gregoritsch","Sasa Kalajdzic"],
"بلجيكا": ["Thibaut Courtois","Senne Lammens","Mike Penders","Thomas Meunier","Timothy Castagne","Arthur Theate","Zeno Debast","Maxim De Cuyper","Brandon Mechele","Koni De Winter","Joaquin Seys","Nathan Ngoy","Axel Witsel","Kevin De Bruyne","Youri Tielemans","Hans Vanaken","Charles De Ketelaere","Amadou Onana","Nicolas Raskin","Diego Moreira","Romelu Lukaku","Leandro Trossard","Jeremy Doku","Dodi Lukebakio","Alexis Saelemaekers","Matias Fernandez-Pardo"],
"البوسنة والهرسك": ["Nikola Vasilj","Martin Zlomislic","Osman Hadzikic","Sead Kolasinac","Dennis Hadzikadunic","Amar Dedic","Nikola Katic","Tarik Muharemovic","Nihad Mujakic","Stjepan Radeljic","Nidal Celik","Amir Hadziahmetovic","Benjamin Tahirovic","Armin Gigovic","Dzenis Burnic","Ivan Basic","Esmir Bajraktarevic","Amar Memic","Ivan Sunjic","Kerim Alajbegovic","Ermin Mahmic","Edin Dzeko","Ermedin Demirovic","Samed Bazdar","Haris Tabakovic","Jovo Lukic"],
"البرازيل": ["Alisson","Weverton","Ederson","Wesley","Gabriel Magalhaes","Marquinhos","Alex Sandro","Danilo Luiz","Bremer","Leo Pereira","Douglas Santos","Roger Ibanez","Casemiro","Bruno Guimaraes","Fabinho","Danilo Santos","Lucas Paqueta","Vinicius Junior","Matheus Cunha","Neymar","Raphinha","Endrick","Luiz Henrique","Gabriel Martinelli","Igor Thiago","Rayan"],
"الرأس الأخضر": ["Vozinha","Marcio Rosa","CJ dos Santos","Stopira","Diney","Pico","Logan Costa","Joao Paulo","Sidny Cabral","Steven Moreira","Wagner Pina","Kelvin Pires","Kevin Pina","Jamiro Monteiro","Deroy Duarte","Laros Duarte","Yannick Semedo","Telmo Arcanjo","Jovane Cabral","Benchimol","Garry Rodrigues","Willy Semedo","Dailon Livramento","Ryan Mendes","Nuno da Costa","Helio Varela"],
"كندا": ["Dayne St. Clair","Maxime Crepeau","Owen Goodman","Alistair Johnston","Luc de Fougerolles","Alfie Jones","Joel Waterman","Derek Cornelius","Moise Bombito","Alphonso Davies","Richie Laryea","Niko Sigur","Mathieu Choiniere","Stephen Eustaquio","Ismael Kone","Liam Millar","Jacob Shaffelburg","Tajon Buchanan","Ali Ahmed","Jonathan Osorio","Nathan Saliba","Cyle Larin","Jonathan David","Tani Oluwaseyi","Promise David"],
"كولومبيا": ["David Ospina","Camilo Vargas","Alvaro Montero","Daniel Munoz","Jhon Lucumi","Santiago Arias","Yerry Mina","Johan Mojica","Willer Ditta","Deiver Machado","Davinson Sanchez","Kevin Castano","Richard Rios","Jorge Carrascal","James Rodriguez","Jhon Arias","Gustavo Puerta","Juan Camilo Portilla","Jefferson Lerma","Juan Fernando Quintero","Jaminton Campaz","Luis Diaz","Jhon Cordoba","Juan Camilo Hernandez","Luis Suarez","Carlos Andres Gomez"],
"الكونغو الديمقراطية": ["Lionel Mpasi","Timothy Fayulu","Matthieu Epolo","Aaron Wan-Bissaka","Axel Tuanzebe","Chancel Mbemba","Dylan Batubinsika","Steve Kapuadi","Joris Kayembe","Arthur Masuaku","Gedeon Kalulu","Rocky Bushiri","Theo Bongonda","Brian Cipenga","Gael Kakuta","Edo Kayembe","Nathanael Mbuku","Samuel Moutoussamy","Charles Pickel","Noah Sadiki","Cedric Bakambu","Simon Banza","Fiston Mayele","Yoane Wissa","Meschack Elia"],
"ساحل العاج": ["Yahia Fofana","Alban Lafont","Mohamed Kone","Ghislain Konan","Odilon Kossounou","Wilfried Singo","Evan Ndicka","Emmanuel Agbadou","Guela Doue","Ousmane Diomande","Christopher Operi","Franck Kessie","Jean Michael Seri","Ibrahim Sangare","Seko Fofana","Christ Inao Oulai","Parfait Guiagon","Nicolas Pepe","Oumar Diakite","Simon Adingra","Evann Guessand","Amad Diallo","Yan Diomande","Bazoumana Toure","Elye Wahi","Ange-Yoan Bonny"],
"كرواتيا": ["Dominik Livakovic","Dominik Kotarski","Ivor Pandur","Josko Gvardiol","Josip Stanisic","Duje Caleta-Car","Josip Sutalo","Marin Pongracic","Martin Erlic","Luka Vuskovic","Luka Modric","Mateo Kovacic","Nikola Moro","Nikola Vlasic","Martin Baturina","Petar Sucic","Luka Sucic","Kristijan Jakic","Toni Fruk","Mario Pasalic","Andrej Kramaric","Ivan Perisic","Ante Budimir","Igor Matanovic","Petar Musa","Marko Pasalic"],
"كوراساو": ["Eloy Room","Tyrick Bodak","Trevor Doornbusch","Shurandy Sambo","Jurien Gaari","Roshon van Eijma","Sherel Floranus","Armando Obispo","Joshua Brenet","Riechedly Bazoer","Deveron Fonville","Godfried Roemeratoe","Juninho Bacuna","Livano Comenencia","Leandro Bacuna","Tyrese Noslin","Ar'jany Martha","Kevin Felida","Jurgen Locadia","Jeremy Antonisse","Sontje Hansen","Kenji Gorre","Jearl Margaritha","Brandley Kuwas","Gervane Kastaneer","Tahith Chong"],
"المكسيك": ["Guillermo Ochoa","Raul Rangel","Carlos Acevedo","Jesus Gallardo","Cesar Montes","Jorge Sanchez","Johan Vasquez","Israel Reyes","Mateo Chavez","Edson Alvarez","Orbelin Pineda","Roberto Alvarado","Luis Romo","Luis Chavez","Erik Lira","Gilberto Mora","Brian Gutierrez","Obed Vargas","Alvaro Fidalgo","Raul Jimenez","Alexis Vega","Santiago Gimenez","Cesar Huerta","Julian Quinones","Guillermo Martinez","Armando Gonzalez"],
"جنوب أفريقيا": ["Ronwen Williams","Ricardo Goss","Last Chaine","Aubrey Modiba","Khuliso Mudau","Siyabonga Sibisi","Mbekezeli Mbokazi","Sipho Okon","Innocent Kabini","Sphephelo Ndamane","Thabo Matuludi","Bongokuhle Sebelebele","Terrence Cross","Lebohang Makhanya","Teboho Mokoena","Sipho Sithole","Sphesihle Mbatha","Lyle Adams","Lebo Zwane","Lyle Foster","Evidence Makgopa","Iqraam Rayners","Relebohile Mofokeng","Oswin Appollis","Lesedi Maseko","Asanele Moremi"],
"التشيك": ["Matej Kovar","Jindrich Stanek","Lukas Hornicek","Vladimir Coufal","Tomas Holes","Ladislav Krejci","David Zima","Jaroslav Zeleny","David Jurasek","David Doudera","Robin Hranac","Stepan Chaloupek","Tomas Soucek","Vladimir Darida","Lukas Provod","Michal Sadilek","Pavel Sulc","Lukas Cerv","Hugo Sochurek","Alexandr Sojka","Denis Visinsky","Patrik Schick","Adam Hlozek","Jan Kuchta","Mojmir Chytil","Tomas Chory"],
"الإكوادور": ["Hernan Galindez","Moises Ramirez","Gonzalo Valle","Felix Torres","Piero Hincapie","Joel Ordonez","Willian Pacho","Pervis Estupinan","Angelo Preciado","Jackson Porozo","Jordy Alcivar","Denil Castillo","John Yeboah","Kendry Paez","Alan Minda","Pedro Vite","Gonzalo Plata","Alan Franco","Moises Caicedo","Yaimar Medina","Kevin Rodriguez","Enner Valencia","Anthony Valencia","Jordy Caicedo","Nilson Angulo","Jeremy Arevalo"],
"مصر": ["Mohamed El-Shenawy","Mostafa Shobeir","El-Mahdy Soliman","Mohamed Alaa","Mohamed Hany","Tarek Alaa","Hamdi Fathy","Ramy Rabia","Yasser Ibrahim","Hossam Abdelmaguid","Mohamed Abdelmonem","Ahmed Fattouh","Karim Hafez","Marwan Attia","Mohannad Lasheen","Nabil Emad","Mahmoud Saber","Emam Ashour","Ahmed Sayed Zizo","Ibrahim Adel","Mostafa Zico","Mohamed Salah","Omar Marmoush","Mahmoud Trezeguet","Hamza Abdelkarim","Haitham Hassan"],
"إنجلترا": ["Dean Henderson","Jordan Pickford","James Trafford","Dan Burn","Trevoh Chalobah","Marc Guehi","Reece James","Ezri Konsa","Nico O'Reilly","Jarell Quansah","Djed Spence","John Stones","Elliot Anderson","Jude Bellingham","Eberechi Eze","Jordan Henderson","Kobbie Mainoo","Declan Rice","Morgan Rogers","Anthony Gordon","Harry Kane","Noni Madueke","Marcus Rashford","Bukayo Saka","Ivan Toney","Ollie Watkins"],
"فرنسا": ["Mike Maignan","Brice Samba","Robin Risser","Lucas Digne","Malo Gusto","Lucas Hernandez","Theo Hernandez","Ibrahima Konate","Jules Kounde","Maxence Lacroix","William Saliba","Dayot Upamecano","N'Golo Kante","Manu Kone","Adrien Rabiot","Aurelien Tchouameni","Warren Zaire-Emery","Maghnes Akliouche","Bradley Barcola","Rayan Cherki","Ousmane Dembele","Desire Doue","Jean-Philippe Mateta","Kylian Mbappe","Michael Olise","Marcus Thuram"],
"ألمانيا": ["Manuel Neuer","Oliver Baumann","Alexander Nubel","Antonio Rudiger","Waldemar Anton","Jonathan Tah","Nico Schlotterbeck","Nathaniel Brown","David Raum","Malick Thiaw","Aleksandar Pavlovic","Joshua Kimmich","Leon Goretzka","Jamie Leweling","Jamal Musiala","Pascal Gross","Angelo Stiller","Leroy Sane","Nadiem Amiri","Felix Nmecha","Lennart Karl","Kai Havertz","Nick Woltemade","Maximilian Beier","Florian Wirtz","Deniz Undav"],
"كوريا الجنوبية": ["Kim Seung-gyu","Song Bum-keun","Jo Hyeon-woo","Han-beom","Kim Min-jae","Tae-hyeon","Park Jin-seob","Seol Young-woo","Tae-seok","Wi-je","Moon-hwan","Jens","Gi-hyuk","Hwang In-beom","Baek Seung-ho","Lee Jae-sung","Hwang Hee-chan","Jun-ho","Lee Kang-in","Jin-gyu","Ji-sung","Lee Dong-gyeong","Son Heung-min","Cho Gue-sung","Oh Hyeon-gyu","Yang Hyun-jun"],
"قطر": ["Mahmoud Abunada","Salah Zakaria","Meshaal Barsham","Pedro Miguel","Lucas Mendes","Gueye","Jassem Gaber","Ayoub Al-Alawi","Homam Ahmed","Boualem Khoukhi","Sultan Al-Brake","Al-Hashemi Al-Hussein","Abdulaziz Hatem","Karim Boudiaf","Ahmed Al-Ghanem","Ahmed Fathy","Asim Madibo","Ahmed Alaaeldin","Edmilson Junior","Mohammed Muntari","Hassan Al-Haydos","Akram Afif","Youssef Abdulrazzaq","Almoez Ali","Tahseen Mohammed","Mohammed Al-Manai"],
"غانا": ["Benjamin Asare","Lawrence Ati-Zigi","Joseph Anang","Baba Abdul Rahman","Gideon Mensah","Marvin Senaya","Alidu Seidu","Abdul Mumin","Jerome Opoku","Jonas Adjetey","Kojo Oppong Peprah","Derrick Luckassen","Elisha Owusu","Thomas Partey","Kwasi Sibo","Augustine Boakye","Caleb Yirenkyi","Abdul Fatawu Issahaku","Kamaldeen Sulemana","Christopher Bonsu Baah","Ernest Nuamah","Antoine Semenyo","Brandon Thomas-Asante","Prince Kwabena Adu","Inaki Williams","Jordan Ayew"],
"هايتي": ["Johny Placide","Alexandre Pierre","Josue Duverger","Ricardo Ade","Carlens Arcus","Martin Experience","Jean-Kevin Duverne","Duke Lacroix","Wilguens Paugain","Hannes Delcroix","Keeto Thermoncy","Leverton Pierre","Danley Jean Jacques","Carl Sainte","Jean-Ricner Bellegarde","Woodensky Pierre","Dominique Simon","Duckens Nazon","Frantzdy Pierrot","Derrick Etienne Jr.","Louicius Deedson","Ruben Providence","Josue Casimir","Yassin Fortune","Wilson Isidor","Lenny Joseph"],
"سويسرا": ["Yann Sommer","Gregor Kobel","Philipp Kohn","Ricardo Rodriguez","Manuel Akanji","Nico Elvedi","Fabian Schar","Silvan Widmer","Eray Comert","Jonathan Jashari","Becir Omeragic","Leonidas Stergiou","Granit Xhaka","Remo Freuler","Fabian Rieder","Vincent Sierro","Ardon Jashari","Denis Zakaria","Michel Aebischer","Liam Chipperfield","Breel Embolo","Ruben Vargas","Zeki Amdouni","Dan Ndoye","Noah Okafor","Johan Manzambi"],
"المغرب": ["Yassine Bounou","Munir","Anas Tagnaouti","Achraf Hakimi","Nayef Aguerd","Noussair Mazraoui","Yahya Belammari","Adam Salah-Eddine","Yahya Riad","Issa Diop","Yasser El Ouahdi","Yasser Halhal","Sofyan Amrabat","Azzedine Ounahi","Eliesse Ben Seghir","Bilal El Khannouss","Ilias Akhomach","Lahcen El Mourabet","Neil El Aynaoui","Achraf El Kaabi","Ayoub El Kaabi","Soufiane Rahimi","Abde Ezzalzouli","Brahim Diaz","Zakaria Aboukhlal","Ismael Saibari"],
"اسكتلندا": ["Craig Gordon","Angus Gunn","Liam Kelly","Andrew Robertson","Grant Hanley","Kieran Tierney","Scott McKenna","Jack Hendry","Anthony Ralston","Aaron Hickey","Ryan Porteous","John Souttar","Kevin Hyam","John McGinn","Scott McTominay","Ryan Christie","Kenny McLean","Lewis Ferguson","Ben Doak","Billy Gilmour","Calvin Bassey","Lyndon Dykes","Che Adams","Lawrence Shankland","Ross Stewart","Tony Watt"],
"الولايات المتحدة": ["Matt Turner","Ethan Horvath","Patrick Schulte","Sergino Dest","Antonee Robinson","Chris Richards","Tim Ream","Miles Robinson","Joe Scally","Walker Zimmerman","Cameron Carter-Vickers","Weston McKennie","Tyler Adams","Yunus Musah","Luca de la Torre","Malik Tillman","Gianluca Busio","Christian Pulisic","Ricardo Pepi","Folarin Balogun","Brenden Aaronson","Timothy Weah","Haji Wright","Gio Reyna","Diego Luna","Patrick Agyemang"],
"باراغواي": ["Carlos Coronel","Roberto Fernandez","Diego Avalos","Gustavo Gomez","Robert Rojas","Alberto Espinola","Junior Alonso","Fabian Balbuena","Mathias Villasanti","Damian Bobadilla","Omar Alderete","Bruno Valdez","Andres Cubas","Gaston Gimenez","Miguel Almiron","Ramon Sosa","Diego Gonzalez","Julio Enciso","Angel Romero","Antonio Sanabria","Adam Bareiro","Alex Arce","Derlis Gonzalez","Ricardo Caballero","Jorge Recalde","Ramon Rodriguez"],
"تركيا": ["Mert Gunok","Altay Bayindir","Ugurcan Cakir","Zeki Celik","Merih Demiral","Caglar Soyuncu","Eren Elmali","Abdulkerim Bardakci","Ozan Kabak","Mert Muldur","Ferdi Kadioglu","Samet Akaydin","Salih Ozcan","Orkun Kokcu","Ismail Yuksek","Kaan Ayhan","Hakan Calhanoglu","Kerem Akturkoglu","Arda Guler","Deniz Gul","Kenan Yildiz","Irfan Can Kahveci","Yunus Akgun","Baris Alper Yilmaz","Oguz Aydin","Can Uzun"],
"هولندا": ["Bart Verbruggen","Mark Flekken","Robin Roefs","Virgil van Dijk","Denzel Dumfries","Nathan Ake","Jurrien Timber","Micky van de Ven","Mats Wieffer","Jan Paul van Hecke","Jorrel Hato","Frenkie de Jong","Marten de Roon","Tijjani Reijnders","Teun Koopmeiners","Ryan Gravenberch","Justin Kluivert","Quinten Timber","Guus Til","Memphis Depay","Wout Weghorst","Donyell Malen","Cody Gakpo","Noa Lang","Brian Brobbey","Crysencio Summerville"],
"اليابان": ["Zion Suzuki","Keisuke Osako","Tomoki Hayakawa","Yukinari Sugawara","Shogo Taniguchi","Ko Itakura","Yuto Nagatomo","Tsuyoshi Watanabe","Ayumu Seko","Hiroki Ito","Takehiro Tomiyasu","Junnosuke Suzuki","Wataru Endo","Ao Tanaka","Takefusa Kubo","Ritsu Doan","Keito Nakamura","Junya Ito","Daichi Kamada","Kaishu Sano","Keisuke Goto","Daizen Maeda","Yuito Suzuki","Ayase Ueda","Koki Ogawa","Kento Shiogai"],
"السويد": ["Jacob Widell Zetterstrom","Viktor Johansson","Kristoffer Nordfeldt","Gustaf Lagerbielke","Victor Lindelof","Isak Hien","Gabriel Gudmundsson","Herman Johansson","Daniel Svensson","Hjalmar Ekdal","Carl Starfelt","Eric Smith","Elliot Stroud","Lucas Bergvall","Jesper Karlstrom","Yasin Ayari","Mattias Svanberg","Besfort Zeneli","Alexander Isak","Benjamin Nygren","Anthony Elanga","Ken Sema","Viktor Gyokeres","Alexander Bernhardsson","Gustaf Nilsson","Taha Ali"],
"تونس": ["Aymen Dahmen","Bechir Ben Said","Ali Abdi","Mohamed Drager","Yassine Meriah","Montassar Talbi","Ali Maaloul","Wajdi Kechrida","Bilel Ifa","Dylan Bronn","Hamza Mathlouthi","Ellyes Skhiri","Aissa Laidouni","Mohamed Amine Ben Amor","Hannibal Mejbri","Naim Sliti","Anis Ben Slimane","Yusuf Sari","Saif-Eddine Jaziri","Seifeddine Jaziri","Issam Jebali","Firas Chaouat","Hazem Haj Hassen","Elias Achouri","Mohamed Ali Ben Romdhane","Omar Rekik"],
"إيران": ["Alireza Beyranvand","Hosein Hoseini","Payam Niazmand","Shoja Khalilzadeh","Hosein Kanaani","Ali Nemati","Daniyal Eiri","Ehsan Hajisafi","Milad Mohammadi","Saleh Hardani","Ramin Rezaiyan","Saman Ghoddos","Saeid Ezatollahi","Rouzbeh Cheshmi","Amir Mohammad Razagh Niya","Mohammed Ghorbani","Mehdi Ghayedi","Ariya Yousefi","Alireza Jahanbakhsh","Mehdi Torabi","Mohammed Mohebbi","Mehdi Taremi","Amirhossein Hosseinzadeh","Denis Dargahi","Ali Alipour","Shahriyar Moghanloo"],
"نيوزيلندا": ["Max Crocombe","Alex Paulsen","Michael Woud","Tim Payne","Francis De Vries","Tyler Bindon","Michael Boxall","Liberato Cacace","Nando Pijnaker","Finn Surman","Callan Elliot","Tommy Smith","Joe Bell","Matt Garbett","Marko Stamenic","Sarpreet Singh","Eli Just","Alex Rufer","Ben Old","Logan McCowatt","Ryan Thomas","Bill Bayliss","Chris Wood","Kosta Barbarouses","Ben Waine","Jake Randall"],
"إسبانيا": ["David Raya","Joan Garcia","Unai Simon","Marc Pubill","Alex Grimaldo","Eric Garcia","Marcos Llorente","Pedro Porro","Aymeric Laporte","Pau Cubarsi","Marc Cucurella","Mikel Merino","Fabian Ruiz","Gavi","Alex Baena","Rodri","Martin Zubimendi","Pedri","Ferran Torres","Dani Olmo","Yeremy Pino","Nico Williams","Lamine Yamal","Mikel Oyarzabal","Victor Munoz","Borja Iglesias"],
"السعودية": ["Nawaf Al Aqidi","Mohammed Al-Owais","Ahmed Al-Kassar","Ali Majrashi","Ali Lajami","Abdulelah Alamri","Hassan Altambakti","Saud Abdulhamid","Nawaf Bu Washl","Hassan Kadish","Moteb Alharbi","Jehad Thikri","Mohammed Abu Alshamat","Nasser Al-Dawsari","Musab Al-Juwayr","Mohammed Alkhaibari","Ziyad Al-Sahafi","Hattan Bahbri","Mohamed Kanno","Ayman Yahya","Feras Al-Buraikan","Salem Al-Dawsari","Saleh Al-Shehri","Khalid Al-Ghannam","Abdullah Al-Hamdan","Sami Al-Najei"],
"الأوروغواي": ["Sergio Rochet","Sebastian Sosa","Fernando Muslera","Jose Maria Gimenez","Sebastian Caceres","Ronald Araujo","Guillermo Varela","Mathias Olivera","Matias Vina","Sebastian Bueno","Manuel Ugarte","Rodrigo Bentancur","Nicolas De La Cruz","Federico Valverde","Giorgian De Arrascaeta","Agustin Canobbio","Mauricio Martinez","Maximiliano Araujo","Joaquin Piquerez","Juan Manuel Sanabria","Rodrigo Zalazar","Darwin Nunez","Facundo Pellistri","Brian Rodriguez","Rodrigo Aguirre","Facundo Vinas"],
"السنغال": ["Yehvann Diouf","Edouard Mendy","Alfousseyni Diaw","Youssouf Sabaly","Kalidou Koulibaly","Abdoulaye Seck","Ismail Jakobs","Krepin Diatta","Moussa Niakhate","Antoine Mendy","El Hadji Malick Diouf","Idrissa Gana Gueye","Pathe Ciss","Lamine Camara","Pape Matar Sarr","Habib Diarra","Bara Sapoko Ndiaye","Pape Gueye","Assane Diao","Boulaye Dia","Sadio Mane","Nicolas Jackson","Cherif Ndiaye","Iliman Ndiaye","Ismaila Sarr","Ibrahim Mbaye"],
"العراق": ["Fahad","Jalal Hassan","Ahmed Basheer","Rebin Sulaka","Hussein Ali","Zaid Tahseen","Manaf Younis","Ahmed Yahya","Merchas Doski","Mustafa Saadoon","Frans Putros","Youssef Amyn","Ibrahim Bayesh","Zidane Iqbal","Amir Al-Ammari","Kevin Yakob","Aimar Sher","Zaid Ismail","Ali Al-Hamadi","Mohanad Ali","Ahmed Qasem","Ali Youssef","Ali Jassim","Aymen Hussein","Marko Farji"],
"النرويج": ["Orjan Nyland","Sander Tangvik","Egil Selvik","Kristoffer Ajer","Leo Ostigard","Birger Wolfe","Fredrik Bjorkan","Jonas Holmgren","Sondre Heggem","Mathias Langas","Andreas Falchener","Morten Thorsby","Sander Berg","Sander Berge","Martin Odegaard","Fredrik Aursnes","Kristian Thorstvedt","Sondre Aasgaard","Jesper Schjelderup","Oscar Bobb","Kristian Hauge","Alexander Sorloth","Erling Haaland","Jorgen Strand Larsen","Antonio Nusa","Julian Ryerson"],
"الأردن": ["Yazeed Abulaila","Abdullah Al-Fakhouri","Noor Bani Attiah","Abdallah Nasib","Ehsan Haddad","Saed Al-Rosan","Saleem Obaid","Yazan Al-Arab","Mohammad Abualnadi","Husam Abu Dahab","Anas Banawi","Mohannad Abu Taha","Mohammad Abu Hasheesh","Noor Al-Rawabdeh","Nizar Al-Rashdan","Ibrahim Saadeh","Rajaei Ayed","Mahmoud Al-Mardi","Amer Jamous","Mohammad Al-Dawoud","Mousa Al-Tamari","Odeh Al-Fakhouri","Mohammad Abu Zrayq","Ali Azaizeh","Ibrahim Sabra","Ali Olwan"],
"البرتغال": ["Diogo Costa","Jose Sa","Rui Silva","Nelson Semedo","Ruben Dias","Tomas Araujo","Diogo Dalot","Renato Veiga","Goncalo Inacio","Joao Cancelo","Samu Aghehowa","Nuno Mendes","Matheus Nunes","Bruno Fernandes","Bernardo Silva","Joao Neves","Ruben Neves","Vitinha","Cristiano Ronaldo","Goncalo Ramos","Joao Felix","Trincao","Rafa Leao","Neto","Goncalo Guedes","Francisco Conceicao"],
"أوزبكستان": ["Utkir Yusupov","Abduvohid Nematov","Rustam Ergashev","Abdukodir Khusanov","Sherzod Alijonov","Khojiakbar Sayfiev","Davron Ashurmatov","Otabek Nasrullaev","Sardor Eshmurodov","Farkhod Abdullaev","Ahmadjon Karimov","Bobur Ulmasaliyev","Abbosbek Urozov","Jaloliddin Mozgovoy","Jamshid Shukurov","Sherzod Iskanderov","Eldorbek Xamrobekov","Rustamjon Masharipov","Jasur Urunov","Otabek Khamdamov","Ozodbek Ganiev","Abbosbek Fayzullaev","Jasurbek Esanov","Eldor Shomurodov","Asilbek Amonov","Igor Sergeev"],
"بنما": ["Luis Mejia","Cesar Samudio","Orlando Mosquera","Cesar Blackman","Jose Cordoba","Fidel Escobar","Edgardo Farina","Jiovany Ramos","Carlos Harvey","Eric Davis","Andres Andrade","Amir Murillo","Roderick Miller","Jorge Gutierrez","Cristian Martinez","Jose Luis Rodriguez","Adalberto Carrasquilla","Ismael Diaz","Yoel Barcenas","Alberto Quintero","Anibal Godoy","Cesar Yanis","Tomas Rodriguez","Jose Fajardo","Cecilio Waterman","Azarias Londono"]
}

print(len(rosters), "teams")
total = 0
for k, v in rosters.items():
    total += len(v)
    if len(v) < 24:
        print("LOW COUNT:", k, len(v))
print("total players:", total)

with open("scripts/rosters.json", "w", encoding="utf-8") as f:
    json.dump(rosters, f, ensure_ascii=False, indent=2)
print("written")
